# -*- coding: utf-8 -*-
"""hw3_fairness_audit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQJBWmyycnIi4c3jqoLEBaMxDS2xUq30

# HW3: Fairness & Bias Audit in Mental Health Data
## Logistic Regression vs Neural Network
## Fairness Mitigation using Threshold Adjustment

## 1. Import Libraries
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

"""## 2. Load Dataset

"""

df = pd.read_csv("HW3_mental_health_diagnosis_treatment.csv")

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

"""## 3. Define Label, Protected Attribute, and Features

"""

# Encode label Y
df["Outcome_Binary"] = df["Outcome"].map({
    "Improved": 1,
    "Deteriorated": 0
})

# Encode protected attribute A
df["Gender_Binary"] = df["Gender"].map({
    "Female": 0,
    "Male": 1
})

# Define feature columns (do NOT include Gender)
feature_cols = [
    "Age",
    "Diagnosis",
    "Symptom Severity (1-10)",
    "Mood Score (1-10)",
    "Sleep Quality (1-10)",
    "Physical Activity (hrs/week)",
    "Medication",
    "Therapy Type",
    "Treatment Duration (weeks)",
    "Stress Level (1-10)",
    "Treatment Progress (1-10)",
    "AI-Detected Emotional State",
    "Adherence to Treatment (%)"
]

X = df[feature_cols].copy()
y = df["Outcome_Binary"].copy()
A = df["Gender_Binary"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("A shape:", A.shape)

"""## 4. Encode Categorical Variables

"""

categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
print("Categorical columns:", categorical_cols)

X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

print("Encoded X shape:", X_encoded.shape)
print(X_encoded.head())

"""## 5. Train-Test Split

"""

X_train, X_test, y_train, y_test, A_train, A_test = train_test_split(
    X_encoded, y, A, test_size=0.3, random_state=42
)

print("Training set size:", X_train.shape[0])
print("Testing set size:", X_test.shape[0])

"""## 6. Train Logistic Regression

"""

lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)
y_prob_lr = lr_model.predict_proba(X_test)[:, 1]

print("Logistic Regression model trained successfully.")

"""## 7. Train Neural Network

"""

mlp_model = MLPClassifier(
    hidden_layer_sizes=(8, 8),
    max_iter=1000,
    random_state=42
)

mlp_model.fit(X_train, y_train)

y_pred_mlp = mlp_model.predict(X_test)
y_prob_mlp = mlp_model.predict_proba(X_test)[:, 1]

print("Neural Network (MLP) trained successfully.")

"""## 8. Evaluate Overall Performance

"""

def overall_metrics(y_true, y_pred):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0)
    }

lr_overall = overall_metrics(y_test, y_pred_lr)
mlp_overall = overall_metrics(y_test, y_pred_mlp)

overall_results = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Accuracy": round(lr_overall["Accuracy"], 4),
        "Precision": round(lr_overall["Precision"], 4),
        "Recall": round(lr_overall["Recall"], 4)
    },
    {
        "Model": "Neural Network (MLP)",
        "Accuracy": round(mlp_overall["Accuracy"], 4),
        "Precision": round(mlp_overall["Precision"], 4),
        "Recall": round(mlp_overall["Recall"], 4)
    }
])

print("=== Overall Performance ===")
print(overall_results)

"""## 9. Evaluate Fairness by Group

"""

def compute_group_metrics(y_true, y_pred):
    acc = accuracy_score(y_true, y_pred)

    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    tpr = tp / (tp + fn) if (tp + fn) > 0 else 0
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0

    return acc, tpr, fpr

def evaluate_by_group(y_true, y_pred, protected_attr):
    results = []

    for group_value, group_name in [(0, "Female"), (1, "Male")]:
        mask = (protected_attr == group_value)

        group_y_true = y_true[mask]
        group_y_pred = y_pred[mask]

        acc, tpr, fpr = compute_group_metrics(group_y_true, group_y_pred)

        results.append({
            "Group": group_name,
            "Accuracy": round(acc, 4),
            "TPR": round(tpr, 4),
            "FPR": round(fpr, 4),
            "Count": int(mask.sum())
        })

    return pd.DataFrame(results)

# Logistic Regression group results
lr_group_results = evaluate_by_group(y_test, y_pred_lr, A_test)
lr_group_results.insert(0, "Model", "Logistic Regression")

# Neural Network group results
mlp_group_results = evaluate_by_group(y_test, y_pred_mlp, A_test)
mlp_group_results.insert(0, "Model", "Neural Network (MLP)")

group_results = pd.concat([lr_group_results, mlp_group_results], ignore_index=True)

print("=== Group Fairness Results ===")
print(group_results)

"""## 10. Apply Fairness Mitigation

"""

female_threshold = 0.50
male_threshold = 0.40

y_pred_lr_adjusted = np.zeros_like(y_prob_lr, dtype=int)

y_pred_lr_adjusted[(A_test == 0) & (y_prob_lr > female_threshold)] = 1
y_pred_lr_adjusted[(A_test == 1) & (y_prob_lr > male_threshold)] = 1

print("Threshold adjustment applied.")

"""## 11. Compare Before vs After

"""

before_group = evaluate_by_group(y_test, y_pred_lr, A_test)
before_group.insert(0, "Version", "Before Mitigation")

after_group = evaluate_by_group(y_test, y_pred_lr_adjusted, A_test)
after_group.insert(0, "Version", "After Mitigation")

mitigation_results = pd.concat([before_group, after_group], ignore_index=True)

print("=== Before vs After Mitigation ===")
print(mitigation_results)

# To compare fairness gaps
def compute_fairness_gap(group_df):
    female_row = group_df[group_df["Group"] == "Female"].iloc[0]
    male_row = group_df[group_df["Group"] == "Male"].iloc[0]

    tpr_gap = abs(female_row["TPR"] - male_row["TPR"])
    fpr_gap = abs(female_row["FPR"] - male_row["FPR"])

    return round(tpr_gap, 4), round(fpr_gap, 4)

before_tpr_gap, before_fpr_gap = compute_fairness_gap(before_group)
after_tpr_gap, after_fpr_gap = compute_fairness_gap(after_group)

before_accuracy = accuracy_score(y_test, y_pred_lr)
after_accuracy = accuracy_score(y_test, y_pred_lr_adjusted)

gap_comparison = pd.DataFrame([
    {
        "Version": "Before Mitigation",
        "TPR Gap": before_tpr_gap,
        "FPR Gap": before_fpr_gap,
        "Accuracy": round(before_accuracy, 4)
    },
    {
        "Version": "After Mitigation",
        "TPR Gap": after_tpr_gap,
        "FPR Gap": after_fpr_gap,
        "Accuracy": round(after_accuracy, 4)
    }
])

print("=== Fairness Gap Comparison ===")
print(gap_comparison)

"""## 12. Conclusion"""

print("=== Conclusion ===")
print("1. Logistic Regression and Neural Network models were trained.")
print("2. Both models were evaluated using overall metrics: accuracy, precision, and recall.")
print("3. Fairness was evaluated across gender groups using accuracy, TPR, and FPR.")
print("4. Threshold adjustment was applied to Logistic Regression as the fairness mitigation method.")
print("5. Before and after mitigation results were compared to see whether fairness improved.")

"""## Save Results into csv file"""

overall_results.to_csv("overall_results.csv", index=False)
group_results.to_csv("group_fairness_results.csv", index=False)
mitigation_results.to_csv("mitigation_results.csv", index=False)
gap_comparison.to_csv("fairness_gap_comparison.csv", index=False)

print("All result files saved.")